// Generated by https://quicktype.io

class Area {
  int id;
  String descripcion;
  String nombre;
  String imagen;

  Area({
    this.id,
    this.descripcion,
    this.nombre,
    this.imagen,
  });

  Area.fromJSON(Map<String, dynamic> json) {
    id = json['id'];
    descripcion = json['descripcion'];
    nombre = json['nombre'];
    imagen = json['imagen'];
  }
}
