// Generated by https://quicktype.io

class CitaModel {
  int codigo;
  int areaId;
  DateTime fecha;
  String horaInicio;
  String horaFin;
  String area;
  String docName;
  String docLastName;
  int estado;

  CitaModel({
    this.codigo,
    this.fecha,
    this.horaInicio,
    this.horaFin,
    this.area,
    this.estado,
    this.docName,
    this.docLastName,
    this.areaId,
  });

  CitaModel.fromJSON(Map<String, dynamic> json) {
    codigo = json['codigo'];
    fecha = DateTime.parse(json['fecha']);
    horaInicio = json['hora_inicio'];
    horaFin = json['hora_fin'];
    area = json['area_nombre'];
    estado = json['estado'];
    docName = json['doctor_nombre'];
    docLastName = json['doctor_apellido'];
    areaId = json['area_id'];
  }

  String get state {
    String stateFinal = '';
    switch (estado) {
      case 1:
        stateFinal = 'ATENDIDA';
        break;
      case 3:
        stateFinal = 'CANCELADA';
        break;
      case 2:
        stateFinal = 'POSTERGADA';
        break;
      case 4:
        stateFinal = 'PENDIENTE';
        break;
    }
    return stateFinal;
  }

  String get cod {
    String cad = codigo.toString();
    while (cad.length < 8) {
      cad = '0' + cad;
    }
    return 'CM-' + cad;
  }

  String get fechaCita {
    String aux = fecha.toString().substring(0, 10);
    List<String> date = aux.split('-');
    return "${date[2]}/${date[1]}/${date[0]}";
  }

  String get hora {
    bool isPMInicio = false, isPMFin = false;
    if (int.parse(horaInicio.substring(0, 2)) > 11) isPMInicio = true;
    if (int.parse(horaFin.substring(0, 2)) > 11) isPMFin = true;
    String horaFinal = '';
    if (isPMInicio == isPMFin)
      horaFinal = isPMInicio
          ? horaInicio.substring(0, 5) + ' - ' + horaFin.substring(0, 5) + ' pm'
          : horaInicio.substring(0, 5) +
              ' - ' +
              horaFin.substring(0, 5) +
              ' am';
    else
      horaFinal = horaInicio.substring(0, 5) +
          ' am - ' +
          horaFin.substring(0, 5) +
          ' pm';
    return horaFinal;
  }

  String get doctor => docName + ' ' + docLastName;
}
