// Generated by https://quicktype.io

class Doctor {
  int id;
  String nombre;
  String apellido;
  String carnet;
  String imagen;
  String imagenLast;
  String nameLast;
  int total;

  Doctor({
    this.id,
    this.nombre,
    this.apellido,
    this.carnet,
    this.imagen,
    this.imagenLast,
    this.total,
    this.nameLast,
  });

  Doctor.fromJSON(Map<String, dynamic> json) {
    id = json['id'];
    nombre = json['nombre'];
    apellido = json['apellido'];
    carnet = json['carnet'];
    imagen = json['imagen'];
    imagenLast = json['last'].length > 0 ? json['last'][0]['imagen'] ?? "" : "";
    total = json['last'].length > 0 ? json['last'][0]['total'] : 0;
    nameLast = json['last'].length > 0 ? json['last'][0]['nombre'] : "";
  }

  String get nombreCompleto => nombre + ' ' + apellido;
}
