// Generated by https://quicktype.io

class Horario {
  int id;
  String horaInicio;
  String horaFin;
  int consultorio;
  int condicion;

  Horario({
    this.id,
    this.horaInicio,
    this.horaFin,
    this.consultorio,
    this.condicion,
  });

  Horario.fromJSON(Map<String, dynamic> json) {
    id = json['id'];
    horaInicio = json['hora_inicio'];
    horaFin = json['hora_fin'];
    consultorio = json['consultorio'];
    condicion = json['condicion'];
  }

  String get hora {
    bool isPMInicio = false, isPMFin = false;
    if (int.parse(horaInicio.substring(0, 2)) > 11) isPMInicio = true;
    if (int.parse(horaFin.substring(0, 2)) > 11) isPMFin = true;
    String horaFinal = '';
    if (isPMInicio == isPMFin)
      horaFinal = isPMInicio
          ? horaInicio.substring(0, 5) + ' - ' + horaFin.substring(0, 5) + ' pm'
          : horaInicio.substring(0, 5) +
              ' - ' +
              horaFin.substring(0, 5) +
              ' am';
    else
      horaFinal = horaInicio.substring(0, 5) +
          ' am - ' +
          horaFin.substring(0, 5) +
          ' pm';
    return horaFinal;
  }
}
