// Generated by https://quicktype.io

class Receta {
  int id;
  String numero;
  String createdAt;
  int citaId;
  String doctorNombre;
  String doctorApellido;
  List<Medicamento> medicamentos;

  Receta({
    this.id,
    this.numero,
    this.createdAt,
    this.citaId,
    this.doctorNombre,
    this.doctorApellido,
    this.medicamentos,
  });

  Receta.fromJSON(Map<String, dynamic> json) {
    id = json['id'];
    numero = json['numero'];
    createdAt = json['created_at'];
    citaId = json['cita_id'];
    doctorNombre = json['doctor_nombre'];
    doctorApellido = json['doctor_apellido'];
    List<Medicamento> aux = [];
    for (var item in json['medicamentos']) {
      final med = Medicamento.fromJSON(item);
      aux.add(med);
    }
    medicamentos = aux;
  }

  String get fechaCita {
    String aux = createdAt.toString().substring(0, 10);
    List<String> date = aux.split('-');
    return "${date[2]}/${date[1]}/${date[0]}";
  }

  String get cod {
    String cad = citaId.toString();
    while (cad.length < 8) {
      cad = '0' + cad;
    }
    return 'CM-' + cad;
  }
}

class Medicamento {
  int id;
  String nombre;
  String descripcion;
  String imagen;
  dynamic dosis;
  dynamic frecuencia;

  Medicamento({
    this.id,
    this.nombre,
    this.descripcion,
    this.imagen,
    this.dosis,
    this.frecuencia,
  });

  Medicamento.fromJSON(Map<String, dynamic> json) {
    id = json['id'];
    nombre = json['nombre'];
    descripcion = json['descripcion'];
    imagen = json['imagen'];
    dosis = json['dosis'];
    frecuencia = json['frecuencia'];
  }
}
